<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gnss" nsURI="http://inavet.de/datamodels" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="GNSS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datetime" eType="ecore:EDataType ../utils/utils.ecore#//ZonedDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../utils/utils.ecore#//NMEA"
        defaultValueLiteral="GPRMC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nmeastring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journey" eType="ecore:EClass ../journey/journey.ecore#//Journey"/>
  </eClassifiers>
</ecore:EPackage>
