<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gnss" nsURI="http://inavet.de/datamodels" nsPrefix="gnss">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="utils" value="#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="GNSS">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="GNSS-Datum vom Smartphone / der mobilen Anwendung zum Datenbroker&#xA;wird mind. sekündlich vom der Smartphone / der mobilen Anwendung zum Datenbroker gesendet&#xA;Root-Klasse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Datenbroker-id"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
        eType="ecore:EDataType ../utils/utils.ecore#//ZonedDateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Zeitstempel der Datum-Erzeugung"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EEnum ../utils/utils.ecore#//NMEAType"
        defaultValueLiteral="GPRMC">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="nmea-type zur späteren Filterung auf dem Datenbroker"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nmeastring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="der eigentliche nmea-String der Anwendung"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="journey" lowerBound="1"
        eType="ecore:EClass ../journey/journey.ecore#//Journey" eKeys="../journey/journey.ecore#//Journey/id">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="journey bzw. journey-id zur Zuweisung des nmea-strings zur entsprechenden Fahrt"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
