<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gnss" nsURI="http://inavet.de/datamodels" nsPrefix="">
  <eClassifiers xsi:type="ecore:EEnum" name="NMEA">
    <eLiterals name="GNRMC"/>
    <eLiterals name="GNGGA" value="3"/>
    <eLiterals name="GPGGA" value="2"/>
    <eLiterals name="GPRMC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GNSS">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datetime" eType="#//ZonedDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="journey" eType="#//Journey"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NMEA" defaultValueLiteral="GPRMC"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nmeastring" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Journey" instanceClassName="models.journey"/>
  <eClassifiers xsi:type="ecore:EDataType" name="ZonedDateTime" instanceClassName="java.time.ZonedDateTime">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="native Type, auf dem Zielsystem vorhanden"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
