<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="camMsg" nsURI="http://tud/etsi/its/cooperativeAwareness" nsPrefix="camMsg">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="camMsg" value="#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="CAM">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="CAM message with header and payload."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="header" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//ItsPduHeader">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="ITS PDU header of the CAM. This DF includes DEs for the CAM&#xA;protocolVersion, the CAM message type identifier messageID and the station&#xA;identifier stationID of the originating ITS-S.&#xA;The DE protocolVersion is used to select the appropriate protocol decoder at&#xA;the receiving ITS-S.&#xA;This DE messageID should be harmonized with other V2X message identifier&#xA;definitions"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cam" lowerBound="1" eType="#//CoopAwareness"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoopAwareness">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="CAM payload. It shall include the time stamp of the CAM and the containers&#xA;basicContainer and highFrequency Container. The selection of the&#xA;highFrequency Container depends on the ITS station type. CAM payload may&#xA;include the additional containers lowFrequencyContainer and&#xA;specialVehicleContainer. The selection of the additional containers depends on&#xA;the ITS station type and other criteria, e.g. vehicle role."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generationDeltaTime" lowerBound="1"
        eType="ecore:EDataType ../CommonDataDict/commonDataDict.ecore#//GenerationDeltaTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="camParameters" lowerBound="1"
        eType="#//CamParameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CamParameter">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The sequence of CAM mandatory and optional containers.&#xA;Other containers may be added in the future. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicContainer" lowerBound="1"
        eType="#//BasicContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="highFrequencyContainer"
        lowerBound="1" eType="#//HighFrequencyContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lowFrequencyContainer"
        eType="#//LowFrequencyContainer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HighFrequencyContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The mandatory high frequency container of CAM."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicVehicleContainerHighFrequency"
        lowerBound="1" eType="#//BasicVehicleContainerHighFrequency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LowFrequencyContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The low frequency container of CAM."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basicVehicleContainerLowFrequency"
        lowerBound="1" eType="#//BasicVehicleContainerLowFrequency"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The mandatory basic container of CAM. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stationType" lowerBound="1"
        eType="ecore:EEnum ../CommonDataDict/commonDataDict.ecore#//StationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencePosition" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//ReferencePosition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicVehicleContainerHighFrequency">
    <eStructuralFeatures xsi:type="ecore:EReference" name="heading" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//Heading"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="speed" lowerBound="1" eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//Speed"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="driveDirection" lowerBound="1"
        eType="ecore:EEnum ../CommonDataDict/commonDataDict.ecore#//DriveDirection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicleLength" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//VehicleLength"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleWidth" lowerBound="1"
        eType="ecore:EDataType ../CommonDataDict/commonDataDict.ecore#//VehicleWidth"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="longitudinalAcceleration"
        lowerBound="1" eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//LongitudinalAcceleration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="curvature" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//Curvature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="curvatureCalculationMode"
        lowerBound="1" eType="ecore:EEnum ../CommonDataDict/commonDataDict.ecore#//CurvatureCalculationMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="yawRate" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//YawRate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BasicVehicleContainerLowFrequency">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The mandatory high frequency container of the CAM when the originating ITS-S&#xA;is of the type vehicle ITS-S. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleRole" lowerBound="1"
        eType="ecore:EEnum ../CommonDataDict/commonDataDict.ecore#//VehicleRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exteriorLights" lowerBound="1"
        eType="ecore:EDataType ../CommonDataDict/commonDataDict.ecore#//ExteriorLights"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathHistory" lowerBound="1"
        eType="ecore:EClass ../CommonDataDict/commonDataDict.ecore#//PathHistory"/>
  </eClassifiers>
</ecore:EPackage>
