<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="basicInitialData">
  <eClassifiers xsi:type="ecore:EClass" name="BasicInitialData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="BasicInitialData " value="zur Übermittlung der notwendigen FAS-Aktivierungs-Information"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" lowerBound="1"
        eType="ecore:EDataType ../utils/utils.ecore#//ZonedDateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleIdList" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fasRegistry" lowerBound="1"
        eType="#//FASRegistry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lineCourseRouteInformation"
        lowerBound="1" eType="#//LineCourseRouteInformation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FASRegistry">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="FasRegistry" value="Geräteaktivierung-> Registrierung am Datenbroker"/>
      <details key="id" value="Datenbroker-Id"/>
      <details key="deviceId" value="eindeutige, unveränderliche, lebenszeitdefinierte Geräte-Id"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineCourseRouteInformation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="LineCourseRouteInformation" value="Line->Course->Route Klasse Lines Maped auf Course, Course auf Route, Route enthält den Fahrweg"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lines" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="course" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="route" lowerBound="1">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
