<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="utils">
  <eClassifiers xsi:type="ecore:EDataType" name="ZonedDateTime" instanceClassName="java.time.ZonedDateTime"/>
  <eClassifiers xsi:type="ecore:EEnum" name="NMEA">
    <eLiterals name="GNRMC"/>
    <eLiterals name="GNGGA" value="3"/>
    <eLiterals name="GPGGA" value="2"/>
    <eLiterals name="GPRMC" value="1"/>
  </eClassifiers>
</ecore:EPackage>
